name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install pyinstaller

      - name: Build binary (Linux)
        run: |
          source .venv/bin/activate
          pyinstaller --onefile --windowed gui_convert.py
          mv dist/gui_convert youtube2ultrastar

      - name: Upload artifact (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: youtube2ultrastar-linux
          path: youtube2ultrastar

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv .venv
          .\.venv\Scripts\activate
          pip install --upgrade pip
          pip install pyinstaller

      - name: Build binary (Windows)
        run: |
          .\.venv\Scripts\activate
          pyinstaller --onefile --windowed gui_convert.py
          mv dist\gui_convert.exe youtube2ultrastar.exe

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: youtube2ultrastar-windows
          path: youtube2ultrastar.exe

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/youtube2ultrastar-linux/youtube2ultrastar
            artifacts/youtube2ultrastar-windows/youtube2ultrastar.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

